name: CI

on: [push, pull_request]

env:
  RUST_BACKTRACE: 1

jobs:
  - uses: actions/checkout@v2
  - name: Install latest nightly
    uses: actions-rs/toolchain@v1
    with:
      toolchain: nightly
      override: true
      components: rustfmt, clippy

  check:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [ stable, nightly ]
        use_std: [ y, n ]
    steps:
      - uses: actions/checkout@v2

      # Test with std
      - uses: actions-rs/toolchain@v1
        name: Toolchain setup
        if: ${{ matrix.use_std == 'y' }}
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
      - uses: actions-rs/cargo@v1
        name: Test
        if: ${{ matrix.use_std == 'y' }}
        with:
          command: test

      # Test on nostd
      - uses: actions-rs/toolchain@v1
        name: Toolchain setup
        if: ${{ matrix.use_std == 'n' }}
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          target: thumbv6m-none-eabi
          override: true
      - uses: actions-rs/cargo@v1
        name: Test
        if: ${{ matrix.use_std == 'n' }}
        with:
          command: build
          args: --target thumbv6m-none-eabi --no-default-features

  doc-check:
    name: Doc check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Toolchain setup
        with:
          profile: minimal
          toolchain: stable
      - uses: actions-rs/install@v0.1
        name: Install cargo-deadlinks
        with:
          crate: cargo-deadlinks
          version: 0.8.0
      - name: Run cargo-deadlinks
        run: cargo deadlinks

